# Generated by Django 2.2.5 on 2021-05-26 15:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20210503_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(max_length=80, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='room-photos', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(max_length=140, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Amenity', verbose_name='편의시설'),
        ),
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.IntegerField(verbose_name='화장실 개수'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(verbose_name='방 개수'),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(verbose_name='침대 개수'),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.TimeField(verbose_name='체크인'),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(verbose_name='체크아웃'),
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(max_length=80, verbose_name='도시'),
        ),
        migrations.AlterField(
            model_name='room',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='국가'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='room',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Facility', verbose_name='기타'),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='How many people will staying?', verbose_name='최대 가능 게스트 수'),
        ),
        migrations.AlterField(
            model_name='room',
            name='house_rules',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.HouseRule', verbose_name='주의사항'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=140, verbose_name='숙소명'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(verbose_name='요금'),
        ),
    ]
