# Generated by Django 2.2.5 on 2021-06-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20210625_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-created',)},
        ),
    ]
